<?php

namespace MS\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function FindAllTeacher()
    {

        $queryBuilder = $this->createQueryBuilder('teacher');
        $queryBuilder->where('teacher.roles LIKE :role')
                     ->setParameter('role', '%ROLE_TEACHER%')
                     ->orderBy('teacher.first_name')
                     ->orderBy('teacher.last_name');
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }
}