#services:
#    ms_platform.example:
#        class: MS\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
services:
  redirect.after.login:
    class: MS\PlatformBundle\Listener\AfterLoginRedirection
    arguments: ['@router']
  logout_success_handler:
    class: MS\PlatformBundle\Listener\LogoutSuccessHandler
    arguments: ['@router']