# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        MS\PlatformBundle\Entity\User : bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_TEACHER: ROLE_USER
        ROLE_STUDENT: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout:
                path:   /logout
                target: /
                success_handler: logout_success_handler
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login
                require_previous_session: false
            remember_me:
                secret: '%secret%'
                lifetime: 604800

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/teacher, roles: ROLE_TEACHER }
        - { path: ^/student, roles: ROLE_STUDENT }
#        - { path: /admin, roles: ROLE_ADMIN, IS_AUTHENTICATED_REMEMBERED }


